repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.2.0  # Use the latest version
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest version
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Use the latest version
    hooks:
      - id: mypy
