"""add skus for distinguish

Revision ID: 41fbaa6565f9
Revises: d30c598d8682
Create Date: 2025-08-10 14:44:42.691960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fbaa6565f9'
down_revision: Union[str, Sequence[str], None] = 'd30c598d8682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('variant_sku', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'product_variants', ['variant_sku'])
    op.drop_column('product_variants', 'color')
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'products', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'sku')
    op.add_column('product_variants', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_variants', type_='unique')
    op.drop_column('product_variants', 'variant_sku')
    # ### end Alembic commands ###
