"""add unique for question

Revision ID: 8fb4a5f1ad5f
Revises: 6aec2c725722
Create Date: 2025-07-30 11:15:54.929012

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8fb4a5f1ad5f"
down_revision: Union[str, Sequence[str], None] = "6aec2c725722"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_question"), table_name="knowledge")
    op.create_index(
        op.f("ix_knowledge_question"), "knowledge", ["question"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_question"), table_name="knowledge")
    op.create_index(
        op.f("ix_knowledge_question"), "knowledge", ["question"], unique=False
    )
    # ### end Alembic commands ###
