"""add images

Revision ID: c1b8c1f576d3
Revises: e81f2cc8d0d9
Create Date: 2025-08-21 02:29:45.243524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b8c1f576d3'
down_revision: Union[str, Sequence[str], None] = 'e81f2cc8d0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'order')
    # ### end Alembic commands ###
