"""update unique key

Revision ID: e81f2cc8d0d9
Revises: 6576c6993895
Create Date: 2025-08-16 01:17:37.330215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81f2cc8d0d9'
down_revision: Union[str, Sequence[str], None] = '6576c6993895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_line_name', 'product_lines', ['name', 'brand_id', 'category_id'])
    op.create_unique_constraint('uq_product_variant_tag', 'product_variant_tags', ['variant_id', 'tag_id'])
    op.create_unique_constraint('uq_product_variant_name_product', 'product_variants', ['name', 'product_id'])
    op.create_unique_constraint(None, 'product_variants', ['name'])
    op.create_unique_constraint('uq_product_name_product_line', 'products', ['name', 'product_line_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_name_product_line', 'products', type_='unique')
    op.drop_constraint(None, 'product_variants', type_='unique')
    op.drop_constraint('uq_product_variant_name_product', 'product_variants', type_='unique')
    op.drop_constraint('uq_product_variant_tag', 'product_variant_tags', type_='unique')
    op.drop_constraint('uq_product_line_name', 'product_lines', type_='unique')
    # ### end Alembic commands ###
